# Generated by Django 5.2.7 on 2026-02-09 21:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=500)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('kpp', models.CharField(blank=True, max_length=9)),
                ('ogrn', models.CharField(blank=True, max_length=15)),
                ('legal_address', models.TextField(blank=True)),
                ('actual_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('blocked', 'Заблокирована'), ('pending', 'На модерации')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.account')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.company')),
            ],
            options={
                'verbose_name': 'контакт компании',
                'verbose_name_plural': 'контакты компаний',
                'db_table': 'company_contact',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.equipmentcategory')),
            ],
            options={
                'verbose_name': 'категория техники',
                'verbose_name_plural': 'категории техники',
                'db_table': 'equipment_category',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=150)),
                ('specifications', models.JSONField(default=dict)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('condition', models.CharField(choices=[('new', 'Новая'), ('used', 'Б/У'), ('refurbished', 'Восстановленная')], default='new', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_lease_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('leased', 'В лизинге'), ('maintenance', 'На обслуживании'), ('sold', 'Продана')], default='available', max_length=50)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('images_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment', to='core.equipmentcategory')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.manufacturer')),
            ],
            options={
                'verbose_name': 'техника',
                'verbose_name_plural': 'техника',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lease_term_months', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('completed', 'Завершён'), ('terminated', 'Расторгнут')], default='draft', max_length=50)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lease_contracts', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to='core.account')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lease_contracts', to='core.equipment')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to='core.account')),
            ],
            options={
                'verbose_name': 'договор лизинга',
                'verbose_name_plural': 'договоры лизинга',
                'db_table': 'lease_contract',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_at', models.DateField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('service_company', models.CharField(blank=True, max_length=255)),
                ('documents_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='core.account')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.equipment')),
            ],
            options={
                'verbose_name': 'обслуживание',
                'verbose_name_plural': 'обслуживание',
                'db_table': 'maintenance',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критичный')], default='normal', max_length=50)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to='core.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='core.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='core.equipment')),
            ],
            options={
                'verbose_name': 'заявка на обслуживание',
                'verbose_name_plural': 'заявки на обслуживание',
                'db_table': 'maintenance_request',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='core.role'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='ru', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.account')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.account')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'журнал аудита',
                'db_table': 'audit_log',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='idx_audit_table_record'), models.Index(fields=['performed_at'], name='idx_audit_performed_at')],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], default='pending', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='core.leasecontract')),
            ],
            options={
                'verbose_name': 'платёж по графику',
                'verbose_name_plural': 'графики платежей',
                'db_table': 'payment_schedule',
                'constraints': [models.UniqueConstraint(fields=('contract', 'payment_number'), name='unique_contract_payment_number')],
            },
        ),
    ]
